### ISSUE TITLE
Compat with Apotheosis

### ISSUE THREAD

**Issue by anna-s-h** [artynova/mediaworks#11]
Apotheosis adds extra levels to many enchantments, and it detects yours as ones to attempt adding extra levels to, but the higher levels do not appear to have greater effects, at least not on locale magnification.

Although ensuring useless books isn't generated is probably easier, I would love to see the generated ones function instead

It is possible that it is just using the fact that the levels exist and could be added by commands with only your mod. If that's the case, then this issue is really that your enchantments don't have different behavior at higher levels, which is still strange, for example if an admin wants unlimited ambit

**Comment by artynova** [comment]
Good day. Your suggestion is greatly appreciated, and though we are not planning on adding uncapped scaling, we do want to increase compatibility with Apotheosis (as well as Quark and other mods with over-enchanting capabilities). So, version 1.0.5 of Mediaworks will introduce additional, diminishing bonuses for levels beyond the standard caps for Locale Magnification and Media Shield.
