### ISSUE TITLE
Cloak re-trigges on overcast

### ISSUE THREAD

**Issue by walksanatora** [artynova/mediaworks#13]
if you take overcast dammage the cloak gets triggered which can lead to a infinite loop. which can crash/lag servers
please look into making it so the cloak only triggers overcast damage once (would also be nice if it would keep casting if the entity is alive)

**Comment by artynova** [comment]
Greetings! Have you encountered this behaviour leading to an infinite loop, or are you speaking theoretically? During my playtests, this could lead to a loop that would kill the player, but not crash or lag the server.

**Comment by walksanatora** [comment]
Okay so I asked Chloe for more info
They said that this only occurs when the dammage is "blocked" via something like the Blob origin from Origins++

**Comment by walksanatora** [comment]
Since that origin has a "2nd healthbar" feature where all dammage you take while it has charge deals 2 ticks of dammage to that bar (before dealing normal dammage)

**Comment by walksanatora** [comment]
And yes it is a crash

**Comment by artynova** [comment]
Greetings! I apologize for the delay with mentioning this in the issue thread, but the bug has been addressed in update 1.0.5. Looping has been adopted as an intended mechanic, but limited in number of triggers to avoid crashing. Thank you for reporting this, have a good day!
