### ISSUE TITLE
Forge NPE on cloak mixin

### ISSUE THREAD

**Issue by autumn-birds** [artynova/mediaworks#2]
I threw a bunch of mods in a Forge instance on a whim and got this.  It goes away when I delete everything but Mediaworks' own dependencies, but that's no fun...  I have no idea which mod could be causing this.  😐  If you know an easier way to find out than manually removing and adding the mods back in one by one (I'm using packwiz), it'd be apprecaited.  Or if you can figure out what's happening here.

Here is a [crash report](https://github.com/artynova/mediaworks/files/12729943/crash-2023-09-26_09.31.11-client.txt), I have more where that came from.  I tried removing modernfix (since it was listed in the ... mixins? ... in the stack trace), but it did not help. I also tried with Mediaworks 1.0.0 and that crashed too.  (Actually this is that crash log, here is one with 1.0.1: 
[crash-2023-09-26_09.28.21-client.txt](https://github.com/artynova/mediaworks/files/12729981/crash-2023-09-26_09.28.21-client.txt))

**Comment by artynova** [comment]
Greetings! I have not been able to reproduce the crash, but in Mediaworks 1.0.2 I implemented a fix that should theoretically prevent crashes like these from occurring. Could you please check whether it still happens for you with Mediaworks 1.0.2?

**Comment by artynova** [comment]
Good day @autumn-birds. Are you currently having trouble with this issue? If you do not respond within a week, I will be closing this issue as stale.

**Comment by artynova** [comment]
Closing issue as stale.
