### ISSUE TITLE
Quilt crash with mediaworks + memoryleakfix

### ISSUE THREAD

**Issue by ChloeTax** [artynova/mediaworks#4]
[latest.log](https://mclo.gs/jXfe0bb)
[crash report](https://mclo.gs/CWM9Gln)
[memoryleakfix](https://modrinth.com/mod/memoryleakfix)

**Comment by artynova** [comment]
You have MemoryLeakFix version 1.1.1. Please update it to version 1.1.2, that prevents the crash.
