### ISSUE TITLE
a couple macula suggestions

### ISSUE THREAD

**Issue by beholderface** [artynova/mediaworks#9]
- Currently, both Etch Visage and Macula Erasure produce particles at the caster's position. This means that having a constantly-updating macula HUD system (either via wisps or circlespam) produces constant particles, which can get very annoying. I suggest these particles be disabled, or perhaps have a client-side config.
- Visages that you conjure for <1 second appear already faded. I suggest that the fade logic be changed so that they only fade if they were summoned for >=5 seconds, and any shorter-length visages simply vanish when their remaining time reaches zero.
- Lastly, it seems visages disappear based on client-side time rather than server-side ticks, so <20 TPS can cause regularly-applied macula setups to flicker. I imagine checking server-side ticks instead would solve this.

**Comment by artynova** [comment]
Thank you for the suggestions, now implemented in mod version 1.0.4.
